"""The catalog resync PR is a catalog bump, not a board-card closer.

These tests pin the pure functions in scripts/open_catalog_resync.py: FACTS
stamp surgery, drift lists, PR body contract (no Closes board item, no agent
identity), and the token refusal. GitHub and git are not exercised here.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT = REPO_ROOT / "scripts" / "open_catalog_resync.py"

_FACTS = """## Catalog scale

Two different counters. Do not equate them.

- Live `GET https://sugra.ai/stats` (2026-09-09): 1,641 endpoints, 190 sources, 36 categories. Public copy: "1,500+" / "160+" / 36 domains.
- Bundled MCP catalog (built_at 2026-09-09T19:01:52Z): 1,611 GET/POST operations from live OpenAPI. PyPI 0.10.0 (uploaded 2026-08-20) still carries the pre-2026-09-04 bundle.
"""


def _mod():
    spec = importlib.util.spec_from_file_location("open_catalog_resync", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


def test_update_facts_replaces_count_built_at_and_adds_sha() -> None:
    mod = _mod()
    updated = mod.update_facts(
        _FACTS,
        operation_count=1623,
        spec_sha256="abcdef1234567890" + "0" * 48,
        built_at="2026-09-10T00:00:00Z",
    )

    assert "built_at 2026-09-10T00:00:00Z" in updated
    assert "1,623 GET/POST operations" in updated
    assert "(spec_sha256 abcdef123456...)" in updated
    assert "PyPI 0.10.0 (uploaded 2026-08-20)" in updated
    assert "1,641 endpoints" in updated
    assert "1,611 GET/POST" not in updated
    assert "2026-09-09T19:01:52Z" not in updated


def test_update_facts_is_idempotent_for_the_same_stamp() -> None:
    mod = _mod()
    once = mod.update_facts(
        _FACTS,
        operation_count=1623,
        spec_sha256="abcdef1234567890" + "0" * 48,
        built_at="2026-09-10T00:00:00Z",
    )
    twice = mod.update_facts(
        once,
        operation_count=1623,
        spec_sha256="abcdef1234567890" + "0" * 48,
        built_at="2026-09-10T00:00:00Z",
    )
    assert twice == once


def test_update_facts_fails_when_the_stamp_line_is_missing() -> None:
    mod = _mod()
    with pytest.raises(SystemExit, match="no bundled catalog stamp line"):
        mod.update_facts(
            "## Catalog scale\n\n- Live stats only.\n",
            operation_count=1,
            spec_sha256="a" * 64,
            built_at="2026-01-01T00:00:00Z",
        )


def test_drift_lists_names_missing_extra_and_changed() -> None:
    mod = _mod()
    old = {
        "endpoints": [
            {"operation_id": "keep", "path": "/a"},
            {"operation_id": "gone", "path": "/b"},
            {"operation_id": "moved", "path": "/old"},
        ]
    }
    new = {
        "endpoints": [
            {"operation_id": "keep", "path": "/a"},
            {"operation_id": "added", "path": "/c"},
            {"operation_id": "moved", "path": "/new"},
        ]
    }
    missing, extra, changed = mod.drift_lists(old, new)
    assert missing == ["added"]
    assert extra == ["gone"]
    assert changed == ["moved"]


def test_pr_body_does_not_close_a_board_card_or_name_a_pilot() -> None:
    mod = _mod()
    body = mod.pr_body(
        missing=["census_new"],
        extra=["retired_op"],
        changed=["quotes_symbol_price"],
        spec_url="https://sugra.ai/openapi.json",
        operation_count=1623,
        spec_sha256="ab" * 32,
        built_at="2026-09-10T00:00:00Z",
    )
    lowered = body.lower()
    assert "closes board item" not in lowered
    assert "mcp-15.3" not in lowered
    for name in ("grok", "claude", "codex", "agy", "co-authored-by", "generated by"):
        assert name not in lowered
    assert "census_new" in body
    assert "retired_op" in body
    assert "quotes_symbol_price" in body
    assert "does not close a board card" in body
    assert mod.RESYNC_BRANCH == "ci/catalog-resync"


def test_pr_body_truncates_long_operation_lists() -> None:
    mod = _mod()
    many = [f"op_{i:02d}" for i in range(25)]
    body = mod.pr_body(
        missing=many,
        extra=[],
        changed=[],
        spec_url="https://sugra.ai/openapi.json",
        operation_count=1,
        spec_sha256="a" * 64,
        built_at="2026-09-10T00:00:00Z",
    )
    assert "op_00" in body
    assert "op_19" in body
    assert "op_20" not in body
    assert "and 5 more" in body
    assert "none" in body  # extra and changed empty


def test_require_catalog_token_refuses_github_token_alone() -> None:
    mod = _mod()
    with pytest.raises(SystemExit, match="MCP_CATALOG_TOKEN"):
        mod.require_catalog_token({"GITHUB_TOKEN": "ghs_not_enough"})
    assert mod.require_catalog_token({"MCP_CATALOG_TOKEN": " pat "}) == "pat"
