"""Country-name vocabulary for query geography detection (MCP-9).

GENERATED from pycountry 24.6.1 names/common names plus curated demonyms
and short forms - regenerate rather than hand-edit the big block. Values
are ISO 3166-1 alpha-2 codes; keys are lowercase token phrases.
"""

COUNTRY_QUERY_TERMS: dict[str, str] = {
    "afghanistan": "AF",
    "albania": "AL",
    "algeria": "DZ",
    "america": "US",
    "american": "US",
    "american samoa": "AS",
    "andorra": "AD",
    "angola": "AO",
    "anguilla": "AI",
    "antarctica": "AQ",
    "antigua and barbuda": "AG",
    "argentina": "AR",
    "argentine": "AR",
    "argentinian": "AR",
    "armenia": "AM",
    "armenian": "AM",
    "aruba": "AW",
    "australia": "AU",
    "australian": "AU",
    "austria": "AT",
    "austrian": "AT",
    "azerbaijan": "AZ",
    "azerbaijani": "AZ",
    "bahamas": "BS",
    "bahrain": "BH",
    "bangladesh": "BD",
    "barbados": "BB",
    "belarus": "BY",
    "belgian": "BE",
    "belgium": "BE",
    "belize": "BZ",
    "benin": "BJ",
    "bermuda": "BM",
    "bhutan": "BT",
    "bolivia": "BO",
    "bosnia and herzegovina": "BA",
    "botswana": "BW",
    "bouvet island": "BV",
    "brazil": "BR",
    "brazilian": "BR",
    "britain": "GB",
    "british": "GB",
    "british indian ocean territory": "IO",
    "brunei darussalam": "BN",
    "bulgaria": "BG",
    "bulgarian": "BG",
    "burkina faso": "BF",
    "burundi": "BI",
    "cabo verde": "CV",
    "cambodia": "KH",
    "cameroon": "CM",
    "canada": "CA",
    "canadian": "CA",
    "cape verde": "CV",
    "cayman islands": "KY",
    "central african republic": "CF",
    "chad": "TD",
    "chile": "CL",
    "chilean": "CL",
    "china": "CN",
    "chinese": "CN",
    "christmas island": "CX",
    "cocos (keeling) islands": "CC",
    "colombia": "CO",
    "colombian": "CO",
    "comoros": "KM",
    "congo": "CG",
    "cook islands": "CK",
    "costa rica": "CR",
    "croatia": "HR",
    "cuba": "CU",
    "curaçao": "CW",
    "cyprus": "CY",
    "czech": "CZ",
    "czechia": "CZ",
    "côte d'ivoire": "CI",
    "danish": "DK",
    "denmark": "DK",
    "djibouti": "DJ",
    "dominica": "DM",
    "dominican republic": "DO",
    "dutch": "NL",
    "ecuador": "EC",
    "egypt": "EG",
    "egyptian": "EG",
    "el salvador": "SV",
    "emirati": "AE",
    "english": "GB",
    "equatorial guinea": "GQ",
    "eritrea": "ER",
    "estonia": "EE",
    "estonian": "EE",
    "eswatini": "SZ",
    "ethiopia": "ET",
    "ethiopian": "ET",
    "falkland islands (malvinas)": "FK",
    "faroe islands": "FO",
    "fiji": "FJ",
    "filipino": "PH",
    "finland": "FI",
    "finnish": "FI",
    "france": "FR",
    "french": "FR",
    "french guiana": "GF",
    "french polynesia": "PF",
    "french southern territories": "TF",
    "gabon": "GA",
    "gambia": "GM",
    "georgia": "GE",
    "georgian": "GE",
    "german": "DE",
    "germany": "DE",
    "ghana": "GH",
    "gibraltar": "GI",
    "great britain": "GB",
    "greece": "GR",
    "greek": "GR",
    "greenland": "GL",
    "grenada": "GD",
    "guadeloupe": "GP",
    "guam": "GU",
    "guatemala": "GT",
    "guernsey": "GG",
    "guinea": "GN",
    "guinea-bissau": "GW",
    "guyana": "GY",
    "haiti": "HT",
    "heard island and mcdonald islands": "HM",
    "holy see (vatican city state)": "VA",
    "honduras": "HN",
    "hong kong": "HK",
    "hungarian": "HU",
    "hungary": "HU",
    "iceland": "IS",
    "icelandic": "IS",
    "india": "IN",
    "indian": "IN",
    "indonesia": "ID",
    "indonesian": "ID",
    "iran": "IR",
    "iraq": "IQ",
    "ireland": "IE",
    "irish": "IE",
    "isle of man": "IM",
    "israel": "IL",
    "israeli": "IL",
    "italian": "IT",
    "italy": "IT",
    "ivory coast": "CI",
    "jamaica": "JM",
    "japan": "JP",
    "japanese": "JP",
    "jersey": "JE",
    "jordan": "JO",
    "kazakh": "KZ",
    "kazakhstan": "KZ",
    "kenya": "KE",
    "kenyan": "KE",
    "kiribati": "KI",
    "korean": "KR",
    "kuwait": "KW",
    "kyrgyzstan": "KG",
    "lao people's democratic republic": "LA",
    "laos": "LA",
    "latvia": "LV",
    "latvian": "LV",
    "lebanon": "LB",
    "lesotho": "LS",
    "liberia": "LR",
    "libya": "LY",
    "liechtenstein": "LI",
    "lithuania": "LT",
    "lithuanian": "LT",
    "luxembourg": "LU",
    "macao": "MO",
    "macau": "MO",
    "madagascar": "MG",
    "malawi": "MW",
    "malaysia": "MY",
    "malaysian": "MY",
    "maldives": "MV",
    "mali": "ML",
    "malta": "MT",
    "marshall islands": "MH",
    "martinique": "MQ",
    "mauritania": "MR",
    "mauritius": "MU",
    "mayotte": "YT",
    "mexican": "MX",
    "mexico": "MX",
    "moldova": "MD",
    "monaco": "MC",
    "mongolia": "MN",
    "montenegro": "ME",
    "montserrat": "MS",
    "moroccan": "MA",
    "morocco": "MA",
    "mozambique": "MZ",
    "myanmar": "MM",
    "namibia": "NA",
    "nauru": "NR",
    "nepal": "NP",
    "netherlands": "NL",
    "new caledonia": "NC",
    "new zealand": "NZ",
    "nicaragua": "NI",
    "niger": "NE",
    "nigeria": "NG",
    "nigerian": "NG",
    "niue": "NU",
    "norfolk island": "NF",
    "north korea": "KP",
    "north macedonia": "MK",
    "northern mariana islands": "MP",
    "norway": "NO",
    "norwegian": "NO",
    "oman": "OM",
    "pakistan": "PK",
    "pakistani": "PK",
    "palau": "PW",
    "panama": "PA",
    "papua new guinea": "PG",
    "paraguay": "PY",
    "peru": "PE",
    "peruvian": "PE",
    "philippines": "PH",
    "pitcairn": "PN",
    "poland": "PL",
    "polish": "PL",
    "portugal": "PT",
    "portuguese": "PT",
    "puerto rico": "PR",
    "qatar": "QA",
    "romania": "RO",
    "romanian": "RO",
    "russia": "RU",
    "russian": "RU",
    "russian federation": "RU",
    "rwanda": "RW",
    "réunion": "RE",
    "saint barthélemy": "BL",
    "saint kitts and nevis": "KN",
    "saint lucia": "LC",
    "saint martin (french part)": "MF",
    "saint pierre and miquelon": "PM",
    "saint vincent and the grenadines": "VC",
    "samoa": "WS",
    "san marino": "SM",
    "sao tome and principe": "ST",
    "saudi": "SA",
    "saudi arabia": "SA",
    "scottish": "GB",
    "senegal": "SN",
    "serbia": "RS",
    "seychelles": "SC",
    "sierra leone": "SL",
    "singapore": "SG",
    "singaporean": "SG",
    "sint maarten (dutch part)": "SX",
    "slovak": "SK",
    "slovakia": "SK",
    "slovenia": "SI",
    "solomon islands": "SB",
    "somalia": "SO",
    "south africa": "ZA",
    "south georgia and the south sandwich islands": "GS",
    "south korea": "KR",
    "south sudan": "SS",
    "spain": "ES",
    "spanish": "ES",
    "sri lanka": "LK",
    "sudan": "SD",
    "suriname": "SR",
    "svalbard and jan mayen": "SJ",
    "sweden": "SE",
    "swedish": "SE",
    "swiss": "CH",
    "switzerland": "CH",
    "syria": "SY",
    "syrian arab republic": "SY",
    "taiwan": "TW",
    "tajikistan": "TJ",
    "tanzania": "TZ",
    "thai": "TH",
    "thailand": "TH",
    "timor-leste": "TL",
    "togo": "TG",
    "tokelau": "TK",
    "tonga": "TO",
    "trinidad and tobago": "TT",
    "tunisia": "TN",
    "turkey": "TR",
    "turkish": "TR",
    "turkmenistan": "TM",
    "turks and caicos islands": "TC",
    "tuvalu": "TV",
    "türkiye": "TR",
    "uae": "AE",
    "uganda": "UG",
    "ukraine": "UA",
    "ukrainian": "UA",
    "united arab emirates": "AE",
    "united kingdom": "GB",
    "united states": "US",
    "united states minor outlying islands": "UM",
    "uruguay": "UY",
    "usa": "US",
    "uzbekistan": "UZ",
    "vanuatu": "VU",
    "venezuela": "VE",
    "viet nam": "VN",
    "vietnam": "VN",
    "vietnamese": "VN",
    "wallis and futuna": "WF",
    "welsh": "GB",
    "western sahara": "EH",
    "yemen": "YE",
    "zambia": "ZM",
    "zimbabwe": "ZW",
    "åland islands": "AX",
}
